# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import textprocess_pb2 as textprocess__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in textprocess_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFile = channel.unary_unary(
                '/textprocess.TextService/ProcessFile',
                request_serializer=textprocess__pb2.FileRequest.SerializeToString,
                response_deserializer=textprocess__pb2.PipelineResponse.FromString,
                _registered_method=True)
        self.WordFrequency = channel.unary_unary(
                '/textprocess.TextService/WordFrequency',
                request_serializer=textprocess__pb2.FileRequest.SerializeToString,
                response_deserializer=textprocess__pb2.WordFreqResponse.FromString,
                _registered_method=True)
        self.CompressFile = channel.unary_unary(
                '/textprocess.TextService/CompressFile',
                request_serializer=textprocess__pb2.FileRequest.SerializeToString,
                response_deserializer=textprocess__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DecompressFile = channel.unary_unary(
                '/textprocess.TextService/DecompressFile',
                request_serializer=textprocess__pb2.FileRequest.SerializeToString,
                response_deserializer=textprocess__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DetectLanguage = channel.unary_unary(
                '/textprocess.TextService/DetectLanguage',
                request_serializer=textprocess__pb2.FileRequest.SerializeToString,
                response_deserializer=textprocess__pb2.LangResponse.FromString,
                _registered_method=True)
        self.SentimentAnalysis = channel.unary_unary(
                '/textprocess.TextService/SentimentAnalysis',
                request_serializer=textprocess__pb2.FileRequest.SerializeToString,
                response_deserializer=textprocess__pb2.SentimentResponse.FromString,
                _registered_method=True)
        self.TranslateText = channel.unary_unary(
                '/textprocess.TextService/TranslateText',
                request_serializer=textprocess__pb2.FileRequest.SerializeToString,
                response_deserializer=textprocess__pb2.TranslationResponse.FromString,
                _registered_method=True)


class TextServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WordFrequency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompressFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecompressFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectLanguage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SentimentAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFile,
                    request_deserializer=textprocess__pb2.FileRequest.FromString,
                    response_serializer=textprocess__pb2.PipelineResponse.SerializeToString,
            ),
            'WordFrequency': grpc.unary_unary_rpc_method_handler(
                    servicer.WordFrequency,
                    request_deserializer=textprocess__pb2.FileRequest.FromString,
                    response_serializer=textprocess__pb2.WordFreqResponse.SerializeToString,
            ),
            'CompressFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CompressFile,
                    request_deserializer=textprocess__pb2.FileRequest.FromString,
                    response_serializer=textprocess__pb2.FileResponse.SerializeToString,
            ),
            'DecompressFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DecompressFile,
                    request_deserializer=textprocess__pb2.FileRequest.FromString,
                    response_serializer=textprocess__pb2.FileResponse.SerializeToString,
            ),
            'DetectLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLanguage,
                    request_deserializer=textprocess__pb2.FileRequest.FromString,
                    response_serializer=textprocess__pb2.LangResponse.SerializeToString,
            ),
            'SentimentAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.SentimentAnalysis,
                    request_deserializer=textprocess__pb2.FileRequest.FromString,
                    response_serializer=textprocess__pb2.SentimentResponse.SerializeToString,
            ),
            'TranslateText': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=textprocess__pb2.FileRequest.FromString,
                    response_serializer=textprocess__pb2.TranslationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textprocess.TextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('textprocess.TextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocess.TextService/ProcessFile',
            textprocess__pb2.FileRequest.SerializeToString,
            textprocess__pb2.PipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WordFrequency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocess.TextService/WordFrequency',
            textprocess__pb2.FileRequest.SerializeToString,
            textprocess__pb2.WordFreqResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompressFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocess.TextService/CompressFile',
            textprocess__pb2.FileRequest.SerializeToString,
            textprocess__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecompressFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocess.TextService/DecompressFile',
            textprocess__pb2.FileRequest.SerializeToString,
            textprocess__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocess.TextService/DetectLanguage',
            textprocess__pb2.FileRequest.SerializeToString,
            textprocess__pb2.LangResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SentimentAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocess.TextService/SentimentAnalysis',
            textprocess__pb2.FileRequest.SerializeToString,
            textprocess__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocess.TextService/TranslateText',
            textprocess__pb2.FileRequest.SerializeToString,
            textprocess__pb2.TranslationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
