# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: textprocess.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'textprocess.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11textprocess.proto\x12\x0btextprocess\"0\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"v\n\x10WordFreqResponse\x12\x35\n\x04\x66req\x18\x01 \x03(\x0b\x32\'.textprocess.WordFreqResponse.FreqEntry\x1a+\n\tFreqEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"1\n\x0c\x46ileResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\" \n\x0cLangResponse\x12\x10\n\x08language\x18\x01 \x01(\t\"1\n\x11SentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"X\n\x13TranslationResponse\x12\x13\n\x0bsource_lang\x18\x01 \x01(\t\x12\x13\n\x0btarget_lang\x18\x02 \x01(\t\x12\x17\n\x0ftranslated_text\x18\x03 \x01(\t\"\x9a\x02\n\x10PipelineResponse\x12/\n\x08wordfreq\x18\x01 \x01(\x0b\x32\x1d.textprocess.WordFreqResponse\x12-\n\ncompressed\x18\x02 \x01(\x0b\x32\x19.textprocess.FileResponse\x12+\n\x08language\x18\x03 \x01(\x0b\x32\x19.textprocess.LangResponse\x12\x31\n\tsentiment\x18\x04 \x01(\x0b\x32\x1e.textprocess.SentimentResponse\x12\x35\n\x0btranslation\x18\x05 \x01(\x0b\x32 .textprocess.TranslationResponse\x12\x0f\n\x07timings\x18\x06 \x01(\t2\x8e\x04\n\x0bTextService\x12\x46\n\x0bProcessFile\x12\x18.textprocess.FileRequest\x1a\x1d.textprocess.PipelineResponse\x12H\n\rWordFrequency\x12\x18.textprocess.FileRequest\x1a\x1d.textprocess.WordFreqResponse\x12\x43\n\x0c\x43ompressFile\x12\x18.textprocess.FileRequest\x1a\x19.textprocess.FileResponse\x12\x45\n\x0e\x44\x65\x63ompressFile\x12\x18.textprocess.FileRequest\x1a\x19.textprocess.FileResponse\x12\x45\n\x0e\x44\x65tectLanguage\x12\x18.textprocess.FileRequest\x1a\x19.textprocess.LangResponse\x12M\n\x11SentimentAnalysis\x12\x18.textprocess.FileRequest\x1a\x1e.textprocess.SentimentResponse\x12K\n\rTranslateText\x12\x18.textprocess.FileRequest\x1a .textprocess.TranslationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textprocess_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDFREQRESPONSE_FREQENTRY']._loaded_options = None
  _globals['_WORDFREQRESPONSE_FREQENTRY']._serialized_options = b'8\001'
  _globals['_FILEREQUEST']._serialized_start=34
  _globals['_FILEREQUEST']._serialized_end=82
  _globals['_WORDFREQRESPONSE']._serialized_start=84
  _globals['_WORDFREQRESPONSE']._serialized_end=202
  _globals['_WORDFREQRESPONSE_FREQENTRY']._serialized_start=159
  _globals['_WORDFREQRESPONSE_FREQENTRY']._serialized_end=202
  _globals['_FILERESPONSE']._serialized_start=204
  _globals['_FILERESPONSE']._serialized_end=253
  _globals['_LANGRESPONSE']._serialized_start=255
  _globals['_LANGRESPONSE']._serialized_end=287
  _globals['_SENTIMENTRESPONSE']._serialized_start=289
  _globals['_SENTIMENTRESPONSE']._serialized_end=338
  _globals['_TRANSLATIONRESPONSE']._serialized_start=340
  _globals['_TRANSLATIONRESPONSE']._serialized_end=428
  _globals['_PIPELINERESPONSE']._serialized_start=431
  _globals['_PIPELINERESPONSE']._serialized_end=713
  _globals['_TEXTSERVICE']._serialized_start=716
  _globals['_TEXTSERVICE']._serialized_end=1242
# @@protoc_insertion_point(module_scope)
